In [1]:
import numpy as np

In [6]:
a = np.arange(2,22)

In [7]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [8]:
a.ndim

1

In [9]:
a.shape

(20,)

In [10]:
a.shape = (4,5) #4 rows and 5 columns

In [11]:
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [12]:
a.ndim

2

In [13]:
a.shape

(4, 5)

In [14]:
a.shape = (20,)

In [15]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

## Copy() method

In [16]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [17]:
id(a)

2301409036400

In [18]:
b = a.copy()

In [19]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [20]:
id(b)

2301430438096

In [21]:
#deep copy
c = a

In [22]:
c

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [23]:
id(a)

2301409036400

In [24]:
id(c)

2301409036400

## View()

In [25]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [26]:
d = a.view()

In [27]:
d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [28]:
id(a)

2301409036400

In [29]:
id(d)

2301409036496

In [33]:
a.view(np.int32)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [34]:
a.view(np.int32,np.matrix)

matrix([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21]])

## Sort()

In [35]:
x = np.array([[10,0,19],[3,44,5],[12,65,87]])
x

array([[10,  0, 19],
       [ 3, 44,  5],
       [12, 65, 87]])

In [36]:
#Sort an array in-place.
# default it sorts rowwise
x.sort()

In [37]:
x

array([[ 0, 10, 19],
       [ 3,  5, 44],
       [12, 65, 87]])

In [40]:
# to sort columnwise use axis = 0
x.sort(axis=0)

In [41]:
x

array([[ 0,  5, 19],
       [ 3, 10, 44],
       [12, 65, 87]])

In [42]:
x.ravel()

array([ 0,  5, 19,  3, 10, 44, 12, 65, 87])

In [43]:
# i want to sort elements present in array
x.ravel().sort()

In [44]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

# Lets Manipulate array

# add values

In [45]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

## append()

In [46]:
# Append values to the end of an array.
np.append(x,200)

array([  0,   3,   5,  10,  12,  19,  44,  65,  87, 200])

In [48]:
np.append(x,[200,300])

array([  0,   3,   5,  10,  12,  19,  44,  65,  87, 200, 300])

In [49]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

In [52]:
# i dont want to convert array to 1D
np.append(x,[[10],[20],[30]],axis = 1)

array([[ 0,  3,  5, 10],
       [10, 12, 19, 20],
       [44, 65, 87, 30]])

In [53]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

In [56]:
# add values columnwise
np.append(x,[[10,20,30]],axis = 0)

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87],
       [10, 20, 30]])

## insert()

In [57]:
x.ravel()

array([ 0,  3,  5, 10, 12, 19, 44, 65, 87])

In [58]:
# Insert values along the given axis before the given indices.
# add 15 between 5 and 10
np.insert(x,3,15)

array([ 0,  3,  5, 15, 10, 12, 19, 44, 65, 87])

In [59]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

In [60]:
# how to insert in 2D array???
# if we want to add row then values wil be added columnwise
np.insert(x,1,[[1,2,3]],axis=0)

array([[ 0,  3,  5],
       [ 1,  2,  3],
       [10, 12, 19],
       [44, 65, 87]])

In [61]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

In [ ]:
# Assignment: insert values 100,200,300 columwise at index 2 ( btwn 3 and 5)

## Delete()

In [62]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

In [64]:
x.ravel()

array([ 0,  3,  5, 10, 12, 19, 44, 65, 87])

In [63]:
np.delete(x,4) #removed 12
# when we r not specifying the axis, it converts array into 1D and delete elemnt  

array([ 0,  3,  5, 10, 19, 44, 65, 87])

In [66]:
# i want to delete complete row how????
np.delete(x,1,axis=0)

array([[ 0,  3,  5],
       [44, 65, 87]])

In [67]:
#delete column then axis = 1
np.delete(x,1,axis=1)

array([[ 0,  5],
       [10, 19],
       [44, 87]])

In [68]:
x

array([[ 0,  3,  5],
       [10, 12, 19],
       [44, 65, 87]])

## Concatenate()

In [70]:
a= np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [71]:
b= np.array([[1,0],[5,6]])
b

array([[1, 0],
       [5, 6]])

In [72]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [1, 0],
       [5, 6]])

In [73]:
np.concatenate((a,b),axis=1)

array([[1, 2, 1, 0],
       [3, 4, 5, 6]])

In [74]:
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 1, 0, 5, 6])

## split()

In [79]:
# splits array as differnt segments
e  = np.arange(1,25).reshape(6,4)

In [80]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [81]:
e.shape

(6, 4)

In [82]:
# this is rowwise splitting
np.split(e,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [84]:
# if we want to split columnswise
np.split(e,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [85]:
np.split(e,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [89]:
# when we r splitting the array it should to the equal splitting
np.split(e,5) #this is not equal split

ValueError: array split does not result in an equal division

In [ ]:
# Assignment: hsplit() and vsplit()?????

In [91]:
# I want array with shape 4,5 which should contain all values as False
np.zeros((4,5),dtype='bool')

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [93]:
# I want all diagonal elemnts True and Non diagonal elements false
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [94]:
~np.eye(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [102]:
n = np.ones((4,4))

In [103]:
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
n.diagonal()

array([1., 1., 1., 1.])

In [106]:
n.diagonal()

array([1., 1., 1., 1.])

In [108]:
n[0,0]=0

In [109]:
n

array([[0., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
n[1,1]=0

In [113]:
n[2,2] = 0

In [114]:
n[3,3]=0

In [115]:
n

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 0.]])

In [116]:
n.astype(bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [118]:
np.random.uniform(10.5, 75.5,(4,4))

array([[65.60894782, 34.42546619, 74.74943123, 70.55803674],
       [43.1348694 , 43.52065569, 51.37492459, 33.29283709],
       [44.51936982, 68.0951756 , 47.09399194, 11.41435524],
       [13.70363618, 68.025235  , 64.90560061, 45.89649002]])