# Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/srv/conda/envs/notebook/lib/python3.6/site-packages/numpy/__init__.py'>

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'add', 'add_docs

# Creation of arrays

In [4]:
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [5]:
a = [10,20,30,40]
np.array(a)

array([10, 20, 30, 40])

In [6]:
np.array(('a','b','c'))

array(['a', 'b', 'c'], dtype='<U1')

## it supports indexing + slicing

In [9]:
arr = np.array(a)

In [10]:
arr

array([10, 20, 30, 40])

In [11]:
arr[0] #=ve indexing

10

In [12]:
arr[-1] #using -ve indexing

40

In [13]:
#slicing
a[::-1]

[40, 30, 20, 10]

In [14]:
a[2:]

[30, 40]

## its mutable

In [16]:
arr

array([10, 20, 30, 40])

In [17]:
id(arr)

140358400484016

In [18]:
#change 10 to 100
arr[0] = 100

In [19]:
arr

array([100,  20,  30,  40])

In [20]:
id(arr)

140358400484016

#### here id is not changing and changes persist in the same object hence its mutable

## Homo + hetro. values support

In [21]:
np.array([10,20])

array([10, 20])

In [22]:
np.array(['10',20])

array(['10', '20'], dtype='<U2')

## It supports implicit and explicite typecasting

In [23]:
arr

array([100,  20,  30,  40])

In [24]:
# check data type of elements
arr.dtype

dtype('int64')

In [25]:
help(arr.dtype)

Help on dtype object:

class dtype(builtins.object)
 |  dtype(obj, align=False, copy=False)
 |  
 |  Create a data type object.
 |  
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |  
 |  Parameters
 |  ----------
 |  obj
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  
 |  See also
 |  --------
 |  result_type
 |  
 |  Examples
 |  --------
 |  Using array-scalar 

## explicit conversion of data

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr.astype('float')

array([100.,  20.,  30.,  40.])

In [28]:
arr

array([100,  20,  30,  40])

In [29]:
a2 = arr.astype('float')

In [30]:
a2

array([100.,  20.,  30.,  40.])

In [31]:
a2.dtype

dtype('float64')

In [32]:
a2.__sizeof__()

128

In [33]:
arr.__sizeof__()

128

In [38]:
a3  = arr.astype('int16') #converting int64 to int16

In [39]:
a3

array([100,  20,  30,  40], dtype=int16)

In [40]:
a3.__sizeof__() #size in bytes

104

### lets suppose we have hetro. data

In [41]:
b = np.array([1,2.5,'A'])

In [42]:
b

array(['1', '2.5', 'A'], dtype='<U32')

In [43]:
b.astype('int')

ValueError: invalid literal for int() with base 10: '2.5'

In [44]:
b = np.array([1,2.5,'5'])

In [45]:
b

array(['1', '2.5', '5'], dtype='<U32')

In [46]:
b.astype('int')

ValueError: invalid literal for int() with base 10: '2.5'

In [48]:
int('25')

25

In [49]:
int('2.5')

ValueError: invalid literal for int() with base 10: '2.5'

In [50]:
np.array(['1','3','4'])

array(['1', '3', '4'], dtype='<U1')

In [54]:
np.array(['1','2','4']).astype('int')

array([1, 2, 4])

In [55]:
np.array([12,34.5,(5+6j)])

array([12. +0.j, 34.5+0.j,  5. +6.j])

In [56]:
np.array([12,34.5,(5+6j)]).astype('str')

array(['(12+0j)', '(34.5+0j)', '(5+6j)'], dtype='<U64')

# it follows sequence: int float complex str

In [57]:
np.array([1,0,0,1])

array([1, 0, 0, 1])

In [58]:
# convert bool
np.array([1,0,0,1]).astype('bool')

array([ True, False, False,  True])

In [60]:
np.array([1,23.6,0,'A'])

array(['1', '23.6', '0', 'A'], dtype='<U32')

In [62]:
bool('23.5')

True

In [64]:
np.array([1,23,0,'A']).astype('bool')

ValueError: invalid literal for int() with base 10: 'A'

In [65]:
np.array([12.7,44.5])

array([12.7, 44.5])

In [66]:
np.array([12.7,44.5]).astype('bool')

array([ True,  True])

## False 0 None '' apart from these 4 things everything is True in Python

In [67]:
[11.2,4.5,6.7]

[11.2, 4.5, 6.7]

In [68]:
int([11.2,4.5,6.7])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [69]:
int(11.2)

11

In [71]:
np.array([11.2, 4.5, 6.7]).astype('int')

array([11,  4,  6])

### Difference between List and numpy array???
### Difference between Python array and numpy array??

In [72]:
#add 10 in each element
[11.2, 4.5, 6.7]+10

TypeError: can only concatenate list (not "int") to list

In [73]:
np.array([11.2, 4.5, 6.7]) + 10

array([21.2, 14.5, 16.7])

In [74]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [75]:
np.array([1,2]) + np.array([3,4])

array([4, 6])

# Different ways to create numpy array

In [78]:
np.array([9,8])

array([9, 8])

In [79]:
np.arange(4)

array([0, 1, 2, 3])

In [80]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [82]:
# create array with all Zero's
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
# create zero's array with 3 rows and 4 columns==> 2D array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
# 3D array==> (2,3,3)==> 2 blocks, 3 rows and 3 columns
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [85]:
# create arrays with all 1's
np.ones(4)

array([1., 1., 1., 1.])

In [86]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
# if we want to create an array with own values
np.full(10,4) #shape=10, fill_value=4

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [88]:
# 2 X 2 filled by 100
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

## Identity array

In [89]:
#identity matrix === in which diagonal elements are 1
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [90]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [93]:
np.eye(1,3)

array([[1., 0., 0.]])

In [95]:
np.eye(4,4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.eye(4,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
e = np.identity(4)

In [100]:
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
# transpose array
# row become column and viceversa
e.transpose()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [105]:
e = np.array([[2,3,4],[4,5,6],[7,8,9]])
e

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
e.transpose()

array([[2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

In [107]:
e.T

array([[2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

In [108]:
e

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
np.transpose(e)

array([[2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

In [ ]:
#you have array 
e= array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])
I want to transpose this array using python

In [110]:
e

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])