# Create numpy arrays

In [1]:
import numpy as np

In [5]:
#Return evenly spaced numbers over a specified interval.

#Returns `num` evenly spaced samples, calculated over the
#interval [`start`, `stop`].

np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [7]:
# i want 20 numbers between 2-10
np.linspace(2,10,num=12)

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

In [8]:
# i want to know spacing
np.linspace(2,10,num=12,retstep=True)

(array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
         5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
         9.27272727, 10.        ]),
 0.7272727272727273)

In [9]:
# if we want to exclude stop
np.linspace(2,10,num=12,endpoint=False,retstep=True)

(array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
        5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ,
        8.66666667, 9.33333333]),
 0.6666666666666666)

In [10]:
p = np.linspace(2,10,num=12,endpoint=False,retstep=True)
p

(array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
        5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ,
        8.66666667, 9.33333333]),
 0.6666666666666666)

In [11]:
p[-1]

0.6666666666666666

In [13]:
np.linspace(2,10,num=12,endpoint=False,retstep=True)[1]

0.6666666666666666

In [16]:
p[0][:3]

array([2.        , 2.66666667, 3.33333333])

## random numbers

In [20]:
#Random values in a given shape.
np.random.rand(5)

array([0.12010466, 0.36510881, 0.34879497, 0.74639481, 0.38024153])

In [21]:
np.random.rand(5,5)

array([[0.26571721, 0.12660946, 0.48473237, 0.65925656, 0.22491104],
       [0.64111154, 0.60782979, 0.98223095, 0.12902719, 0.21730028],
       [0.06294334, 0.01935767, 0.16490765, 0.36663912, 0.24919366],
       [0.17949832, 0.92625185, 0.42511896, 0.13960097, 0.81137438],
       [0.84192127, 0.68794183, 0.69573252, 0.57181333, 0.91392069]])

In [22]:
np.random.rand(3,2,2)

array([[[0.2086966 , 0.31151557],
        [0.68603602, 0.18220243]],

       [[0.56039951, 0.03783854],
        [0.22519401, 0.00872085]],

       [[0.70328277, 0.44517235],
        [0.95635254, 0.35691398]]])

In [40]:
#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(low = 5,high = 15)

14

In [48]:
# now i want to generate multiple randint
np.random.randint(low = 5,high = 15,size = 10)

array([13, 13,  9, 12, 11, 14, 13, 14, 13, 11])

In [49]:
# Random int 2D array
np.random.randint(low = 5,high = 15,size = (3,3))

array([[ 6, 10, 12],
       [ 8,  8,  9],
       [10, 11,  5]])

In [53]:
np.random.randint(5,15,(3,3))

array([[14, 10, 12],
       [ 7,  5,  8],
       [10, 13,  7]])

In [58]:
# default dtype is int we can change it
np.random.randint(5,15,(3,3),dtype=np.uint8)

array([[ 6,  7,  9],
       [14, 13,  8],
       [ 5, 11,  8]], dtype=uint8)

In [ ]:
np.random.randn
np.random.random
np.random.random_integers
np.random.choice
np.random.seed

In [59]:
np.random.seed?

In [60]:
np.random.seed(10)

In [61]:
np.random.choice?

In [64]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 2])

In [69]:
np.random.choice(5,3)

array([1, 0, 4])

In [70]:
np.random.random(10)

array([0.29187607, 0.91777412, 0.71457578, 0.54254437, 0.14217005,
       0.37334076, 0.67413362, 0.44183317, 0.43401399, 0.61776698])

In [71]:
np.random.random((4,3))

array([[0.51313824, 0.65039718, 0.60103895],
       [0.8052232 , 0.52164715, 0.90864888],
       [0.31923609, 0.09045935, 0.30070006],
       [0.11398436, 0.82868133, 0.04689632]])

In [72]:
a = np.random.randint(2,15,size=(4,5))

In [73]:
a

array([[13, 14,  3,  6, 12],
       [ 2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14],
       [ 8,  4, 10, 10,  8]])

# Inspect the properties

In [74]:
# find out total number of elements
a.size

20

In [75]:
len(a) #returns no of rows in case of 2D array

4

In [76]:
# check rows and columns
a.shape

(4, 5)

In [77]:
a.shape[0]

4

In [78]:
print('Number of rows:',a.shape[0])
print('Number of columns:',a.shape[1])

Number of rows: 4
Number of columns: 5


In [79]:
#check dtype
a.dtype

dtype('int64')

In [81]:
#convert array to list
a.tolist()

[[13, 14, 3, 6, 12], [2, 10, 14, 7, 6], [9, 10, 10, 4, 14], [8, 4, 10, 10, 8]]

# Shape manipulation

In [82]:
a

array([[13, 14,  3,  6, 12],
       [ 2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14],
       [ 8,  4, 10, 10,  8]])

In [83]:
a.shape

(4, 5)

In [ ]:
# if we have 20 element in above case so we can segment them into different options
10 X 2
2 X 10
5 X 4
1 X 20
20 X 1

2,2,5
5,2,2
2,5,2
2,5,2


## reshape

In [85]:
a

array([[13, 14,  3,  6, 12],
       [ 2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14],
       [ 8,  4, 10, 10,  8]])

In [86]:
# 10 X 2
a.reshape(10,2)

array([[13, 14],
       [ 3,  6],
       [12,  2],
       [10, 14],
       [ 7,  6],
       [ 9, 10],
       [10,  4],
       [14,  8],
       [ 4, 10],
       [10,  8]])

In [87]:
#reverse of above
a.reshape(2,10) #2 rows and 10 columns

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

In [88]:
a

array([[13, 14,  3,  6, 12],
       [ 2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14],
       [ 8,  4, 10, 10,  8]])

In [94]:
a.reshape(2,2,5)

array([[[13, 14,  3,  6, 12],
        [ 2, 10, 14,  7,  6]],

       [[ 9, 10, 10,  4, 14],
        [ 8,  4, 10, 10,  8]]])

In [95]:
a

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

# resize: inplace the shape change

In [90]:
a.shape

(4, 5)

In [91]:
a.resize(2,10)

In [92]:
a

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

In [93]:
a.shape

(2, 10)

In [96]:
a

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

In [97]:
a.resize(2,2,5)

In [98]:
a

array([[[13, 14,  3,  6, 12],
        [ 2, 10, 14,  7,  6]],

       [[ 9, 10, 10,  4, 14],
        [ 8,  4, 10, 10,  8]]])

In [99]:
a.shape

(2, 2, 5)

#### What is difference and similarity between reshape and resize????

In [100]:
a

array([[[13, 14,  3,  6, 12],
        [ 2, 10, 14,  7,  6]],

       [[ 9, 10, 10,  4, 14],
        [ 8,  4, 10, 10,  8]]])

In [101]:
# 3D to 2D 
a.shape

(2, 2, 5)

In [102]:
a.resize(2,10)

In [103]:
a

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

In [104]:
a.shape

(2, 10)

In [105]:
a.ndim

2

In [106]:
# 2D/3D to 1D
a

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

In [107]:
a.resize(20)

In [108]:
a

array([13, 14,  3,  6, 12,  2, 10, 14,  7,  6,  9, 10, 10,  4, 14,  8,  4,
       10, 10,  8])

In [109]:
a.ndim

1

In [110]:
a.shape

(20,)

In [111]:
a.resize(2,10)

In [112]:
a

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

In [113]:
#if we want to convert 2D array into 1D temp. 
a.reshape(20)

array([13, 14,  3,  6, 12,  2, 10, 14,  7,  6,  9, 10, 10,  4, 14,  8,  4,
       10, 10,  8])

In [115]:
a.ravel()

array([13, 14,  3,  6, 12,  2, 10, 14,  7,  6,  9, 10, 10,  4, 14,  8,  4,
       10, 10,  8])

In [116]:
a.flatten()

array([13, 14,  3,  6, 12,  2, 10, 14,  7,  6,  9, 10, 10,  4, 14,  8,  4,
       10, 10,  8])

#### Que: difference between ravel() and flatten()????

In [118]:
np.linspace(1,20,12).dtype

dtype('float64')

In [120]:
np.linspace(1,20,12,dtype=int)

array([ 1,  2,  4,  6,  7,  9, 11, 13, 14, 16, 18, 20])

In [121]:
np.linspace(1,20,12)

array([ 1.        ,  2.72727273,  4.45454545,  6.18181818,  7.90909091,
        9.63636364, 11.36363636, 13.09090909, 14.81818182, 16.54545455,
       18.27272727, 20.        ])

In [122]:
a

array([[13, 14,  3,  6, 12,  2, 10, 14,  7,  6],
       [ 9, 10, 10,  4, 14,  8,  4, 10, 10,  8]])

In [123]:
a.shape

(2, 10)

In [ ]:
a.reshape(6,3)