In [1]:
import numpy as np

In [2]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Indexing

In [4]:
a.shape

(4, 5)

In [5]:
# indexing works on row
a[0]

array([1, 2, 3, 4, 5])

In [7]:
a[3]

array([16, 17, 18, 19, 20])

In [8]:
# use -ve indexing
a[-1]

array([16, 17, 18, 19, 20])

In [11]:
a[-1] = [0,0,0,1,1]

In [12]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 0,  0,  0,  1,  1]])

## slicing

In [13]:
# If we want to access multiple rows then use slicing
a[:2] # [start:stop]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
#acccess last 2 rows
a[2:]

array([[11, 12, 13, 14, 15],
       [ 0,  0,  0,  1,  1]])

In [16]:
# 1st and 3rd row
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [18]:
#reverse sequence
a[::-1]

array([[ 0,  0,  0,  1,  1],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [19]:
# Assignment:
# how to access random rows???
# 1,3,4
# 4,1,2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 0,  0,  0,  1,  1]])

In [20]:
#Access columns using slicing
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 0,  0,  0,  1,  1]])

In [22]:
a[:,:3] # [row,column]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [ 0,  0,  0]])

In [27]:
#column starting with 2 & 3
a[:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [ 0,  0]])

In [28]:
# column starting with 4 & 5
a[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [ 1,  1]])

## Slicing for row and columns combination

In [30]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 0,  0,  0,  1,  1]])

In [33]:
# fetch 7,8 & 12,13
a[1:-1,1:3]

array([[ 7,  8],
       [12, 13]])

In [34]:
# replace above selection using 1,2 3,4 resp
a[1:-1,1:3] = [[ 1,  2],[4, 3]]

In [35]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  1,  2,  9, 10],
       [11,  4,  3, 14, 15],
       [ 0,  0,  0,  1,  1]])

In [38]:
# select 4,5 & 9,10 and replace by 20
a[:2,3:] = 20

In [39]:
a

array([[ 1,  2,  3, 20, 20],
       [ 6,  1,  2, 20, 20],
       [11,  4,  3, 14, 15],
       [ 0,  0,  0,  1,  1]])

In [ ]:
# Assignment: I want to set all corner element(1,20,0,1) to 0
# select 6,1 & 11,4 replace by 1,2,3,4 resp
# if i want to replace single element from array???

In [45]:
a[2:,-1]

array([15,  1])

In [47]:
a[2:,-1:]

array([[15],
       [ 1]])

In [48]:
a

array([[ 1,  2,  3, 20, 20],
       [ 6,  1,  2, 20, 20],
       [11,  4,  3, 14, 15],
       [ 0,  0,  0,  1,  1]])

# Conditional selection

In [51]:
# Select element >8 from array a
a>8

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [ True, False, False,  True,  True],
       [False, False, False, False, False]])

In [52]:
# to get output use above bool array as an index
a[a>8]

array([20, 20, 20, 20, 11, 14, 15])

In [53]:
# If we want to merge 2 conditions a>8 and a<20
(a>8)

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [ True, False, False,  True,  True],
       [False, False, False, False, False]])

In [56]:
(a<20)

array([[ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [58]:
# lets combine them 
(a>8) & (a<20)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False,  True,  True],
       [False, False, False, False, False]])

In [64]:
a[(a>8) & (a<20)]

array([11, 14, 15])

# Scalar Maths

In [65]:
a

array([[ 1,  2,  3, 20, 20],
       [ 6,  1,  2, 20, 20],
       [11,  4,  3, 14, 15],
       [ 0,  0,  0,  1,  1]])

In [66]:
# add 10 in each element of a
a + 10

array([[11, 12, 13, 30, 30],
       [16, 11, 12, 30, 30],
       [21, 14, 13, 24, 25],
       [10, 10, 10, 11, 11]])

In [67]:
np.add(a,10)

array([[11, 12, 13, 30, 30],
       [16, 11, 12, 30, 30],
       [21, 14, 13, 24, 25],
       [10, 10, 10, 11, 11]])

In [69]:
a += 10 #a = a+10

In [70]:
a

array([[11, 12, 13, 30, 30],
       [16, 11, 12, 30, 30],
       [21, 14, 13, 24, 25],
       [10, 10, 10, 11, 11]])

In [ ]:
np.substract()

In [ ]:
np.multiply()

In [ ]:
np.divide()

In [ ]:
np.power()

# Vector Math

In [80]:
x = np.array([[1,2],[1,1]])
x

array([[1, 2],
       [1, 1]])

In [81]:
y = np.array([[2,2]])
y

array([[2, 2]])

In [82]:
x + y

array([[3, 4],
       [3, 3]])

In [83]:
np.add(x,y)

array([[3, 4],
       [3, 3]])

In [79]:
# Check subtract, multiply, divide, power..


array([[3, 4],
       [3, 3]])

In [84]:
x == y

array([[False,  True],
       [False, False]])

In [85]:
x

array([[1, 2],
       [1, 1]])

In [86]:
y

array([[2, 2]])

In [87]:
np.array_equal(x,y)

False

In [89]:
z = np.array([[1, 2],
       [1, 1]])
z

array([[1, 2],
       [1, 1]])

In [90]:
x

array([[1, 2],
       [1, 1]])

In [91]:
np.array_equal(x,z)

True

In [92]:
# square root of array
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.        , 1.        ]])

In [93]:
np.square(x)

array([[1, 4],
       [1, 1]], dtype=int32)

In [98]:
# trignometry functions
np.sin(a)

array([[-0.99999021, -0.53657292,  0.42016704, -0.98803162, -0.98803162],
       [-0.28790332, -0.99999021, -0.53657292, -0.98803162, -0.98803162],
       [ 0.83665564,  0.99060736,  0.42016704, -0.90557836, -0.13235175],
       [-0.54402111, -0.54402111, -0.54402111, -0.99999021, -0.99999021]])

In [95]:
np.sin(z)

array([[0.84147098, 0.90929743],
       [0.84147098, 0.84147098]])

In [ ]:
np.cos()
np.tan()
np.log()
np.abs()
np.ceil() #to round number to its nearest int value
np.round()

# Statistics 

In [99]:
a

array([[11, 12, 13, 30, 30],
       [16, 11, 12, 30, 30],
       [21, 14, 13, 24, 25],
       [10, 10, 10, 11, 11]])

In [101]:
# mean
np.mean(a)

17.2

In [102]:
a.mean()

17.2

In [103]:
# min
np.min(a)

10

In [104]:
a.min()

10

In [107]:
# max
np.max(a)

30

In [108]:
a

array([[11, 12, 13, 30, 30],
       [16, 11, 12, 30, 30],
       [21, 14, 13, 24, 25],
       [10, 10, 10, 11, 11]])

In [112]:
# if i want row wise and columnwise mean???
a[0].mean()

19.2

In [113]:
#rowwise
np.mean(a,axis=1)

array([19.2, 19.8, 19.4, 10.4])

In [ ]:
#columnswise


In [114]:
# max
np.max(a)

30

In [115]:
np.max(a,axis=0) #columnswise

array([21, 14, 13, 30, 30])

In [116]:
a

array([[11, 12, 13, 30, 30],
       [16, 11, 12, 30, 30],
       [21, 14, 13, 24, 25],
       [10, 10, 10, 11, 11]])

In [117]:
# sum
np.sum(a)

344

In [ ]:
#rowise

#columnwise

In [118]:
#variance
np.var(a)

59.36

In [ ]:
#rowise

#columnwise

In [119]:
#standard Deviation
np.std(a)

7.704544113703289

In [ ]:
#rowise

#columnwise

In [120]:
np.corrcoef(a)

array([[1.        , 0.96724234, 0.7938621 , 0.99743786],
       [0.96724234, 1.        , 0.91936746, 0.98040672],
       [0.7938621 , 0.91936746, 1.        , 0.83216105],
       [0.99743786, 0.98040672, 0.83216105, 1.        ]])